= fish Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:carapace-bin: https://rsteube.github.io/carapace-bin/carapace-bin.html[carapace-bin]
:fish: https://fishshell.com/[fish]
:GNOME-Keyring: https://wiki.gnome.org/Projects/GnomeKeyring[GNOME-Keyring]
:Starship: https://starship.rs/[Starship]

My configuration for the {fish} shell.

== Usage

This repository contains the configuration files for {fish}.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

== Set up

My fish configuration relies on several other utilities: {carapace-bin} for completions, {GNOME-Keyring} for secrets management, and {Starship} for the prompt configuration.
These utilities must be installed before utilizing the configuration.

. Add the `rsteube` user's RPM repository to your system which provides the `carapace-bin` package.
+
./etc/yum.repos.d/rsteube-fury.repo
[,sh]
----
[fury]
name=Gemfury Private Repo
baseurl=https://yum.fury.io/rsteube/
enabled=1
gpgcheck=0
----

. Add the `starship` COPR repository to your system.
+
[,sh]
----
curl -L https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora/atim-starship-fedora.repo \
  | sudo tee /etc/yum.repos.d/atim-starship-fedora.repo
----

. Install the packages.
+
[,sh]
----
sudo rpm-ostree install carapace-bin fish gnome-keyring starship
----

. Reboot for the changes to take effect.
+
[,sh]
----
sudo systemctl reboot
----

=== Install

Install these settings with the following instructions.

. Clone this repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/fish-config.git
----

. Create the _~/.config/fish/conf.d_ directory.
+
[,sh]
----
mkdir ~/.config/fish/conf.d
----

. Copy the configuration files in the `fish/conf.d` directory to the fish configuration directory.
+
[,sh]
----
cp ~/Projects/fish-config/fish/conf.d/*.fish ~/.config/fish/conf.d/
----

=== Update

To update the settings in this repository from an existing installation, follow these steps.

. If you haven't already done so, clone this repository.
+
[,sh]
----
git -C ~/Projects clone git@github.com:jwillikers/fish-config.git
----

. Copy the configuration files in the `~/.config/fish/conf.d` directory to the repository.
+
[,sh]
----
cp ~/.config/fish/conf.d/*.fish ~/Projects/fish-config/fish/conf.d/
----

. Stage the updated file.
+
[,sh]
----
git -C ~/Projects/fish-config add -A
----

. Commit.
+
[,sh]
----
git -C ~/Projects/fish-config commit -m "Update configuration putting all others to shame"
----

. Push the changes back to the central repository.
+
[,sh]
----
git -C ~/Projects/fish-config push
----

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2023 Jordan Williams

== Authors

mailto:{email}[{author}]
