= fish Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:carapace-bin: https://rsteube.github.io/carapace-bin/carapace-bin.html[carapace-bin]
:direnv: https://direnv.net/[direnv]
:fish: https://fishshell.com/[fish]
:just: https://github.com/casey/just[just]
:Starship: https://starship.rs/[Starship]

My configuration for the {fish} shell.

== Usage

This repository contains the configuration files for {fish}.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Install

My fish configuration relies on other utilities: {carapace-bin} for completions, {Starship} for the prompt configuration, and {direnv} for automatic environment set up.

. Follow the install instructions in the https://github.com/jwillikers/starship-config[Starship config repository] to configure the prompt.

. Install {just} by following the instructions in the https://github.com/casey/just?tab=readme-ov-file#installation[installation section].

. Clone this repository.
+
[,sh]
----
git clone git@github.com:jwillikers/fish-config.git
----

. Change to the project's directory.
+
[,sh]
----
cd fish-config
----

. Run `just` to install everything.
+
[,sh]
----
just
----

. On Fedora Atomic systems, reboot for the changes to take effect.
+
[,sh]
----
sudo systemctl reboot
----

. Open a new shell to complete the installation.

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2023-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
